import { myStartOfDay, myStartOfMonth, myStartOfMonthKey } from './timeFormat';

// Which slice of time the Earnings screen is showing, and the instant range
// that slice covers.
//
// Kept OUT of lib/queries/earnings.ts deliberately. That module constructs a
// Supabase client at import time, so anything living there can only be tested
// by mocking a network client to exercise date arithmetic. This is the same
// split lib/commissionRate.ts and lib/semver.ts already use: the decision is
// pure, so it lives somewhere a test can just call it.
//
// PERIODS ARE BUCKETED BY MY-LOCAL PICKUP DATE — see the header of
// lib/queries/earnings.ts for why that basis, and what it cost to get wrong.

/** A specific past calendar month, keyed "m:YYYY-MM" (e.g. `m:2026-07`). */
export type EarningsMonthPeriod = `m:${string}`;

export type EarningsPeriod = 'week' | 'month' | 'all' | EarningsMonthPeriod;

/** Wraps a "YYYY-MM" key into the period value the hook takes. */
export const monthPeriod = (monthKey: string): EarningsMonthPeriod => `m:${monthKey}`;

/**
 * The "YYYY-MM" inside a month period, or null for the three fixed periods.
 *
 * Note `'month'` does NOT start with `'m:'`, so "this month" and "a named
 * month" stay cleanly separable despite the shared first letter.
 */
export function monthKeyOf(p: EarningsPeriod): string | null {
  return p.startsWith('m:') ? p.slice(2) : null;
}

/**
 * The half-open `[since, until)` instant range a period covers, as ISO strings.
 * `null` means unbounded on that end.
 *
 * Boundaries are pinned to Malaysia, matching lib/timeFormat.ts. These used to
 * use setHours(0,0,0,0) and new Date(y, m, 1), both device-local — so a phone
 * outside MY selected a different window than the dates rendered beside it. The
 * month case was the worst: on a UTC-negative device the local month can still
 * be the previous one, so "This month" silently covered an extra month.
 *
 * `until` exists for past months and only for past months. The three original
 * periods all run to "now" and so never needed an upper bound — which is why
 * the query had none, and why adding a past month WITHOUT one would have
 * quietly returned every job from that month onwards, labelled as that month.
 */
export function periodRange(
  p: EarningsPeriod,
  now: Date = new Date(),
): { since: string | null; until: string | null } {
  if (p === 'all') return { since: null, until: null };
  // Last 7 days INCLUSIVE — a Sunday-start week would diverge across locales,
  // so anchor at "start of the MY day 6 days ago".
  if (p === 'week') return { since: myStartOfDay(now, -6).toISOString(), until: null };
  if (p === 'month') return { since: myStartOfMonth(now).toISOString(), until: null };

  const key = monthKeyOf(p);
  const start = key === null ? new Date(NaN) : myStartOfMonthKey(key);
  // A malformed key can only come from a caller bug — every key the UI offers
  // is generated by monthKeysDesc. Throwing surfaces it; both alternatives are
  // worse, because "fall back to all time" and "return an empty range" each
  // render a plausible-looking total that silently answers a different question.
  if (Number.isNaN(start.getTime())) {
    throw new Error(`Unparseable earnings month period: ${p}`);
  }
  return {
    since: start.toISOString(),
    until: myStartOfMonthKey(key!, 1).toISOString(),
  };
}
